name: ✨ Feature Request
description: Suggest a new idea or improvement.
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What is your idea?
      description: Explain the feature you want added.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What problem does this feature solve?
      description: State why this feature is necessary.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there other ways you have considered?
